spring.application.name=domu

spring.datasource.url=${URL_BBDD}
spring.datasource.username=${USR_BBDD}
spring.datasource.password=${PSW_BBDD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
# spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
